name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    name: Test on Node ${{ matrix.node-version }}
    uses: fastify/workflows/.github/workflows/plugins-ci-redis.yml@v5
    with:
      lint: true
      license-check: true
    secrets: inherit
